# Sección events, es obligatoria
events {
    worker_connections 1024;  # Número máximo de conexiones por trabajador
}

# Sección http, donde definimos los servidores
http {
    # Definimos el servidor
    server {
        listen 8080;
        server_name localhost;

        # Configuración para la raíz de los archivos estáticos
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }

        # Configuración para los archivos subidos (.rsc)
        location /upload/ {
            root /opt/sara/uploads;
            autoindex on;
        }

        # Configuración para mostrar los resultados de la auditoría
        location /results/ {
            root /opt/sara/results;
            autoindex on;
        }

        # Limitar el tamaño de los archivos subidos
        client_max_body_size 10M;
    }
}

